module.exports = {
    "acetylfentanyl": ["drug"],
    "acid": ["drug"],
    "aerosols": ["drug"],
    "agaric": ["drug"],
    "alcohol": ["drug"],
    "alpha-methyltryptamine": ["drug"],
    "alprazolam": ["drug"],
    "amani": ["drug"],
    "amphetamine": ["drug"],
    "amphetamine sulphate": ["drug"],
    "amsterdam gold": ["drug"],
    "amt": ["drug"],
    "methyl ethylamine": ["drug"],
    "amyls": ["drug"],
    "anabolic steroids": ["drug"],
    "angel dust": ["drug"],
    "annihilation": ["drug"],
    "ayahuasca": ["drug"],
    "baccy": ["drug"],
    "banshee dust": ["drug"],
    "bath salts": ["drug"],
    "benzo fury": ["drug"],
    "benzodiazepines": ["drug"],
    "benzofuran compounds": ["drug"],
    "benzos": ["drug"],
    "benzylpiperazine": ["drug"],
    "bevvy": ["drug"],
    "bhang": ["drug"],
    "black mamba": ["drug"],
    "blotter": ["drug"],
    "bolts extra strength": ["drug"],
    "bom-25": ["drug"],
    "bombay blue extreme": ["drug"],
    "supersleep": ["drug"],
    "booze": ["drug"],
    "butane": ["drug"],
    "butylone": ["drug"],
    "bzp": ["drug"],
    "cannabis": ["drug"],
    "carfentanyl": ["drug"],
    "cathinones": ["drug"],
    "chang": ["drug"],
    "chargers": ["drug"],
    "chicken fever": ["drug"],
    "chicken yellow": ["drug"],
    "ching": ["drug"],
    "chroming": ["drug"],
    "co-codamol": ["drug"],
    "codeine": ["drug"],
    "codis500": ["drug"],
    "coke": ["drug"],
    "cosmic kelly": ["drug"],
    "cough syrup": ["drug"],
    "cowies": ["drug"],
    "crack": ["drug"],
    "crank": ["drug"],
    "crystal": ["drug"],
    "crystal meth": ["drug"],
    "d2pm": ["drug"],
    "desoxypipradrol": ["drug"],
    "diamorphine": ["drug"],
    "diazepam": ["drug"],
    "dimethocaine": ["drug"],
    "dimitri": ["drug"],
    "dizzle": ["drug"],
    "dmt": ["drug"],
    "donkey dust": ["drug"],
    "dope": ["drug"],
    "dots": ["drug"],
    "double stacked": ["drug"],
    "downers": ["drug"],
    "dr death": ["drug"],
    "dusting": ["drug"],
    "e-cigarettes": ["drug"],
    "e-cigs": ["drug"],
    "e-hookah": ["drug"],
    "e-liquids": ["drug"],
    "eclipse": ["drug"],
    "ecsess": ["drug"],
    "ecstasy": ["drug"],
    "energy-1": ["drug"],
    "energy1": ["drug"],
    "esp": ["drug"],
    "ethylphenidate": ["drug"],
    "etizolam": ["drug"],
    "euphoria": ["drug"],
    "evoke": ["drug"],
    "exodus": ["drug"],
    "exodus damnation": ["drug"],
    "fast lane": ["drug"],
    "fenazepam": ["drug"],
    "fentanyl": ["drug"],
    "flake": ["drug"],
    "freebase": ["drug"],
    "frenzy": ["drug"],
    "gabapentin": ["drug"],
    "ganja": ["drug"],
    "gbh": ["drug"],
    "gbl": ["drug"],
    "gear": ["drug"],
    "geebs": ["drug"],
    "glue sniffing": ["drug"],
    "gogaine": ["drug"],
    "happy pills": ["drug"],
    "hash": ["drug"],
    "hashish": ["drug"],
    "herb": ["drug"],
    "heroin": ["drug"],
    "hippie crack": ["drug"],
    "hog": ["drug"],
    "holy sage": ["drug"],
    "hookah": ["drug"],
    "hubble bubble": ["drug"],
    "huffing": ["drug"],
    "indopan": ["drug"],
    "inhalants": ["drug"],
    "ivory wave": ["drug"],
    "juice": ["drug"],
    "ket": ["drug"],
    "ketamine": ["drug"],
    "khat": ["drug"],
    "killer": ["drug"],
    "kix": ["drug"],
    "laughing gas": ["drug"],
    "legal e": ["drug"],
    "legal x": ["drug"],
    "liberty caps": ["drug"],
    "lightning flash": ["drug"],
    "linctus": ["drug"],
    "liquid acid": ["drug"],
    "liquid ecstasy": ["drug"],
    "liquid gold": ["drug"],
    "lsd": ["drug"],
    "lyrica": ["drug"],
    "m-cat": ["drug"],
    "m-smack": ["drug"],
    "magic crystals": ["drug"],
    "magic mushrooms": ["drug"],
    "magics": ["drug"],
    "mandy": ["drug"],
    "marijuana": ["drug"],
    "mary joy": ["drug"],
    "melanotan": ["drug"],
    "melanotan": ["drug"],
    "meow meow": ["drug"],
    "meph": ["drug"],
    "mephedrone": ["drug"],
    "mescaline": ["drug"],
    "meth": ["drug"],
    "methadone": ["drug"],
    "methamphetamine": ["drug"],
    "methoxetamine (mxe)": ["drug"],
    "methylnaphthidate": ["drug"],
    "methylone": ["drug"],
    "methylphenidate": ["drug"],
    "mexican magic mint": ["drug"],
    "mexxy": ["drug"],
    "mexy": ["drug"],
    "micro dot": ["drug"],
    "miow": ["drug"],
    "mitsubishi turbo": ["drug"],
    "mitsubishis": ["drug"],
    "mixture": ["drug"],
    "mket": ["drug"],
    "molly": ["drug"],
    "monkey dust": ["drug"],
    "morphine": ["drug"],
    "moxy": ["drug"],
    "mushies": ["drug"],
    "mxe": ["drug"],
    "n-bomb": ["drug"],
    "naphyrone": ["drug"],
    "nemesis": ["drug"],
    "neurontin": ["drug"],
    "new psychoactive substances": ["drug"],
    "nitazenes": ["drug"],
    "nitrous oxide": ["drug"],
    "nootropics": ["drug"],
    "nootropics": ["drug"],
    "nopaine": ["drug"],
    "nos": ["drug"],
    "noz": ["drug"],
    "nps": ["drug"],
    "nrg-1": ["drug"],
    "nrg1": ["drug"],
    "nurofen": ["drug"],
    "opioid": ["drug"],
    "opiate": ["drug"],
    "painkillers": ["drug"],
    "paper mushrooms": ["drug"],
    "party pills": ["drug"],
    "pcp": ["drug"],
    "peace pills": ["drug"],
    "pep love": ["drug"],
    "pep stoned": ["drug"],
    "pep twisted": ["drug"],
    "percy": ["drug"],
    "peyote": ["drug"],
    "peyotebuttons": ["drug"],
    "phenazepam": ["drug"],
    "phencyclidine": ["drug"],
    "philosopher's stones": ["drug"],
    "physeptone": ["drug"],
    "pills": ["drug"],
    "pink ecstasy": ["drug"],
    "pink mcdonalds": ["drug"],
    "pink superman": ["drug"],
    "piperazines": ["drug"],
    "plantfood": ["drug"],
    "pma": ["drug"],
    "pmma": ["drug"],
    "poppers": ["drug"],
    "pot": ["drug"],
    "pregabalin": ["drug"],
    "propylphenidate": ["drug"],
    "puff bars": ["drug"],
    "purple wave": ["drug"],
    "pyrovalerone": ["drug"],
    "qaadka": ["drug"],
    "qat": ["drug"],
    "quat": ["drug"],
    "rapture": ["drug"],
    "red mitsubishi": ["drug"],
    "resin": ["drug"],
    "rhino ket": ["drug"],
    "ritalin": ["drug"],
    "rock hard": ["drug"],
    "roflcoptr": ["drug"],
    "rohypnol": ["drug"],
    "roids": ["drug"],
    "rolexs": ["drug"],
    "roll-ups": ["drug"],
    "rollies": ["drug"],
    "roofies": ["drug"],
    "salvia": ["drug"],
    "seventh-heaven": ["drug"],
    "shisha": ["drug"],
    "shrooms": ["drug"],
    "sildenafil": ["drug"],
    "silver bullet": ["drug"],
    "sinsemilla": ["drug"],
    "skag": ["drug"],
    "skunk": ["drug"],
    "smack": ["drug"],
    "smart drugs": ["drug"],
    "smileypaper": ["drug"],
    "smileys": ["drug"],
    "smilies": ["drug"],
    "sniff": ["drug"],
    "solvents": ["drug"],
    "special k": ["drug"],
    "speed": ["drug"],
    "spice": ["drug"],
    "sulph": ["drug"],
    "super k": ["drug"],
    "superman": ["drug"],
    "synthetic cannabinoids": ["drug"],
    "synthetic opioids": ["drug"],
    "syrup": ["drug"],
    "t-7": ["drug"],
    "tai high hawaiian haze": ["drug"],
    "temazepam": ["drug"],
    "the good stuff": ["drug"],
    "thrust": ["drug"],
    "tina and christine": ["drug"],
    "tnt": ["drug"],
    "tobacco": ["drug"],
    "toot": ["drug"],
    "tooting": ["drug"],
    "tramadol": ["drug"],
    "tramal": ["drug"],
    "tripper": ["drug"],
    "trips": ["drug"],
    "tripstacy": ["drug"],
    "ultram": ["drug"],
    "valium": ["drug"],
    "vallies": ["drug"],
    "vanillasky": ["drug"],
    "vape pens": ["drug"],
    "vape pods": ["drug"],
    "vape sticks": ["drug"],
    "vape": ["drug"],
    "vapes": ["drug"],
    "vitamink": ["drug"],
    "volatile substances": ["drug"],
    "weed": ["drug"],
    "whippits": ["drug"],
    "white magic": ["drug"],
    "whizz": ["drug"],
    "wonk": ["drug"],
    "xanax": ["drug"],
    "xtc": ["drug"],
    "yaba": ["drug"],
}