module.exports = {
    // Sexual for violent lyric searching

    "anal": ["sexual"],
    "analsex": ["sexual"],
    "abortion": ["inappropriate"],

    "bareback": ["sexual"],
    "balls": ["sexual"],
    "ballsack": ["sexual"],
    "batty": ["insult"],
    "battyboy": ["insult"],
    "bender": ["insult"],
    "bdsm": ["sexual"],
    "bisexual": ["inappropriate", "insult"],
    "breast": ["inappropriate", "sexual"],
    "breasts": ["inappropriate", "sexual"],
    "bukkake": ["inappropriate", "sexual"],
    "bummer": ["insult"],

    "cowgirl": ["sexual"],
    "creampie": ["sexual"],
    "creampies": ["sexual"],
    "circumcision": ["inappropriate", "violent"],
    "clitoris": ["inappropriate", "sexual"],
    "condom": ["inappropriate", "violent"],
    "cripple": ["inappropriate", "insult"],
    "cunnilingus": ["sexual"],

    "dilf": ["sexual"],
    "dilfs": ["sexual"],
    "doggystyle": ["sexual"],
    "doggy style": ["sexual"],
    "doggy-style": ["sexual"],

    "erect": ["inappropriate"],
    "erection": ["sexual"],
    "erections": ["sexual"],

    "facial": ["sexual"],
    "fairy": ["insult"],
    "fanny": ["sexual"],
    "fetish": ["sexual"],
    "fingering": ["sexual"],
    "foreplay": ["sexual"],
    "foreskin": ["sexual"],
    "fluffer": ["sexual", "insult"],
    "fudgepacker": ["sexual", "insult"],
    "fudge packer": ["sexual", "insult"],
    "fudge-packer": ["sexual", "insult"],

    "gag": ["sexual"],
    "gags": ["sexual"],
    "gash": ["sexual"],
    "gagging": ["sexual"],
    "genital": ["sexual"],
    "genitals": ["sexual"],
    "gender bender": ["sexual", "insult"],
    "gender-bender": ["sexual", "insult"],

    "hetro": ["inappropriate", "insult"],
    "hetrosexual": ["inappropriate", "insult"],
    "homo": ["inappropriate", "insult"],
    "homosexual": ["inappropriate", "insult"],

    "incest": ["inappropriate", "insult"],
    "infertile": ["inappropriate", "insult"],
    "intercourse": ["inappropriate", "sexual"],

    "knob": ["inappropriate", "sexual", "insult"],

    "labia": ["sexual"],
    "lube": ["sexual"],
    "lubes": ["sexual"],
    "lubrication": ["sexual"],

    "masturbate": ["sexual"],
    "menstruation": ["inappropriate"],
    "milf": ["sexual"],
    "milfs": ["sexual"],
    "minge": ["sexual"],
    "minger": ["insult"],
    "miscarriage": ["inappropriate", "insult"],
    "missionary": ["sexual"],
    "motorboating": ["sexual"],

    "nancy": ["insult"],
    "nipple": ["sexual"],
    "nipples": ["sexual"],
    "nonce": ["insult"],

    "oral": ["inappropriate", "sexual"],
    "orgy": ["sexual"],
    "orgies": ["sexual"],

    "pansy": ["insult"],
    "penis": ["sexual"],
    "pegging": ["sexual"],
    "poof": ["insult"],
    "poofer": ["insult"],
    "pube": ["inappropriate"],
    "pubic": ["inappropriate"],
    "puberty": ["inappropriate"],

    "rape": ["sexual", "violent"],
    "rapes": ["sexual", "violent"],
    "rapey": ["sexual", "violent", "insult"],
    "rapist": ["sexual", "violent"],
    "rapists": ["sexual", "violent"],
    "raping": ["sexual", "violent"],
    "rapings": ["sexual", "violent"],
    "retard": ["insult"],
    "rimming": ["sexual"],

    "shag": ["sexual"],
    "slag": ["sexual", "insult"],
    "sixy nine": ["sexual"],
    "69": ["sexual"],
    "smegma": ["sexual"],
    "semen": ["sexual"],
    "sperm": ["sexual"],
    "sexual": ["sexual"],
    "sexism": ["inappropriate", "violent"],
    "squirting": ["sexual"],
    "sterilisation": ["inappropriate"],
    "strapon": ["sexual"],
    "strap on": ["sexual"],
    "strap-on": ["sexual"],
    "snog": ["inappropriate"],

    "teabagging": ["sexual"],
    "tea bagging": ["sexual"],
    "tea-bagging": ["sexual"],
    "tits": ["sexual"],
    "titty": ["sexual"],
    "tittys": ["sexual"],
    "tittie": ["sexual"],
    "titties": ["sexual"],
    "tranny": ["insult", "sexual"],
    "tribbing": ["sexual"],

    "vagina": ["sexual"],
    "virgin": ["inappropriate"],
    "vibrator": ["sexual"],
    "vibrators": ["sexual"],
    "vulva": ["inappropriate"],

    "underage": ["inappropriate"],
    "underaged": ["inappropriate"],
    "unerect": ["inappropriate"],
    "urine": ["inappropriate"],

    "whore": ["sexual", "insult"],
    "windowlicker": ["insult"],
    "window licker": ["insult"],
    "window-licker": ["insult"],
}